language: node_js
before_install:
    - npx artifactory-npm-setup https://artifactory.brandwatch.com --no-interactive -s @vizia -s @vizia-assets -s @brandwatch -a ${ARTIFACTORY_TOKEN} -u vizia-bot
jobs:
  include:
    - if: type IN (pull_request)
      script: npm run ci
    - if: type NOT IN (pull_request) AND branch = master AND commit_message !~ /chore\(release\)/
      script:
        - npx artifactory-npm-setup https://artifactory.brandwatch.com --no-interactive -s @vizia -s @vizia-assets -s @brandwatch -a ${ARTIFACTORY_TOKEN} -u vizia-bot
        - ./scripts/ci-publish.sh
